export const drawerContentJson = {
  id: "gid://shopify/Menu/206383579394",
  title: "Main Menu",
  items: [
    {
      id: "gid://shopify/Menu/159750127776",
      title: "Women",
      items: [
        {
          id: "gid://shopify/MenuItem/450113700098",
          title: "DRESSES",
          url: "https://campussutra.com/collections/women-dress",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/466164023554",
          title: "CO-ORD SET",
          url: "https://campussutra.com/collections/women-co-ord-set",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/450113601794",
          title: "TOPS & T-SHIRTS",
          url: "https://campussutra.com/collections/women-tops-t-shirts",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/450113667330",
          title: "SHIRT",
          url: "https://campussutra.com/collections/women-casual-shirt",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/465051222274",
          title: "NIGHT SUIT",
          url: "https://campussutra.com/collections/campus-sutra-women-night-suit",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/450113569026",
          title: "SWEATER & SWEATSHIRT",
          url: "https://campussutra.com/collections/women-sweaters-sweatshirts",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/450113732866",
          title: "JACKETS & BLAZERS",
          url: "https://campussutra.com/collections/women-blazer",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/450113765634",
          title: "JEANS",
          url: "https://campussutra.com/collections/women-jeans",
          type: "COLLECTION",
          items: [],
        },
      ],
    },
    {
      id: "gid://shopify/MenuItem/479542706434",
      title: "Men",
      url: "https://campussutra.com/collections/men",
      type: "COLLECTION",
      items: [
        {
          id: "gid://shopify/MenuItem/479542739202",
          title: "T-Shirt",
          url: "https://campussutra.com/collections/men-t-shirt",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/479542771970",
          title: "Casual Shirts",
          url: "https://campussutra.com/collections/men-shirts",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/479542804738",
          title: "Jacket",
          url: "https://campussutra.com/collections/men-jacket",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/479542837506",
          title: "Blazer",
          url: "https://campussutra.com/collections/men-blazer",
          type: "COLLECTION",
          items: [],
        },
        {
          id: "gid://shopify/MenuItem/479542870274",
          title: "Sweater & Sweatshirt",
          url: "https://campussutra.com/collections/men-sweaters-sweateshirt",
          type: "COLLECTION",
          items: [],
        },
      ],
    },
  ],
};
